// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuestionService.Data;

#nullable disable

namespace QuestionService.Data.Migrations
{
    [DbContext(typeof(QuestionDbContext))]
    partial class QuestionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestionService.Data.Models.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("AskerDisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AskerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasAcceptedAnswer")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("TagSlugs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuestionService.Data.Models.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "A composable, opinionated stack for building distributed apps with .NET. Provides dashboard, diagnostics, and simplified service orchestration.",
                            Name = "Aspire",
                            Slug = "aspire"
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                            Description = "A modern, cross-platform development platform for building cloud, web, mobile, desktop, and IoT apps using C# and F#.",
                            Name = ".NET",
                            Slug = "dotnet"
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-9012-cdef-123456789012",
                            Description = "A modern object-database mapper (ORM) for .NET that supports LINQ, change tracking, and migrations for working with relational databases.",
                            Name = "Entity Framework Core",
                            Slug = "ef-core"
                        },
                        new
                        {
                            Id = "d4e5f6a7-b8c9-0123-def0-234567890123",
                            Description = "A cross-platform, high-performance framework for building modern, cloud-enabled, Internet-connected applications including web apps, APIs, and microservices.",
                            Name = "ASP.NET Core",
                            Slug = "aspnet-core"
                        },
                        new
                        {
                            Id = "e5f6a7b8-c9d0-1234-ef01-345678901234",
                            Description = "A framework for building interactive web UIs using C# instead of JavaScript. Supports both server-side and WebAssembly client-side hosting models.",
                            Name = "Blazor",
                            Slug = "blazor"
                        },
                        new
                        {
                            Id = "f6a7b8c9-d0e1-2345-f012-456789012345",
                            Description = "A cross-platform framework for creating native mobile and desktop apps with C# and XAML. Successor to Xamarin.Forms with unified project structure.",
                            Name = ".NET MAUI",
                            Slug = "maui"
                        },
                        new
                        {
                            Id = "a7b8c9d0-e1f2-3456-0123-567890123456",
                            Description = "A simplified approach to building HTTP APIs in ASP.NET Core with minimal code and configuration. Ideal for microservices and small endpoints.",
                            Name = "Minimal APIs",
                            Slug = "minimal-apis"
                        },
                        new
                        {
                            Id = "b8c9d0e1-f2a3-4567-1234-678901234567",
                            Description = "A high-performance messaging and command-handling framework for .NET with built-in support for Mediator, queues, retries, and durable messaging.",
                            Name = "Wolverine",
                            Slug = "wolverine"
                        },
                        new
                        {
                            Id = "c9d0e1f2-a3b4-5678-2345-789012345678",
                            Description = "A real-time communication library for ASP.NET that enables server-to-client messaging over WebSockets, long polling, and more.",
                            Name = "SignalR",
                            Slug = "signalr"
                        },
                        new
                        {
                            Id = "d0e1f2a3-b4c5-6789-3456-890123456789",
                            Description = "A distributed application framework for .NET that provides a consistent abstraction over message transports like RabbitMQ, Azure Service Bus, and Amazon SQS.",
                            Name = "MassTransit",
                            Slug = "masstransit"
                        },
                        new
                        {
                            Id = "e1f2a3b4-c5d6-7890-4567-901234567890",
                            Description = "An open-source message broker that implements AMQP protocol. Enables reliable messaging between distributed systems with routing, queuing, and pub/sub patterns.",
                            Name = "RabbitMQ",
                            Slug = "rabbitmq"
                        },
                        new
                        {
                            Id = "f2a3b4c5-d6e7-8901-5678-012345678901",
                            Description = "A high-performance, open-source RPC framework using Protocol Buffers. Enables efficient communication between microservices with strongly-typed contracts.",
                            Name = "gRPC",
                            Slug = "grpc"
                        },
                        new
                        {
                            Id = "a3b4c5d6-e7f8-9012-6789-123456789012",
                            Description = "A powerful, open-source object-relational database system known for reliability, feature richness, and standards compliance.",
                            Name = "PostgreSQL",
                            Slug = "postgresql"
                        },
                        new
                        {
                            Id = "b4c5d6e7-f8a9-0123-7890-234567890123",
                            Description = "A document-oriented NoSQL database designed for scalability and flexibility. Stores data in JSON-like documents with dynamic schemas.",
                            Name = "MongoDB",
                            Slug = "mongodb"
                        },
                        new
                        {
                            Id = "c5d6e7f8-a9b0-1234-8901-345678901234",
                            Description = "An in-memory data structure store used as database, cache, message broker, and streaming engine. Known for sub-millisecond response times.",
                            Name = "Redis",
                            Slug = "redis"
                        },
                        new
                        {
                            Id = "d6e7f8a9-b0c1-2345-9012-456789012345",
                            Description = "Microsoft's enterprise relational database management system with comprehensive features for transaction processing, analytics, and business intelligence.",
                            Name = "SQL Server",
                            Slug = "sql-server"
                        },
                        new
                        {
                            Id = "e7f8a9b0-c1d2-3456-0123-567890123456",
                            Description = "A globally distributed, multi-model database service by Microsoft Azure. Offers turnkey global distribution, elastic scaling, and multiple consistency models.",
                            Name = "Azure Cosmos DB",
                            Slug = "cosmos-db"
                        },
                        new
                        {
                            Id = "f8a9b0c1-d2e3-4567-1234-678901234567",
                            Description = "An open-source identity and access management solution for modern applications and services. Integrates easily with OAuth2, OIDC, and SSO.",
                            Name = "Keycloak",
                            Slug = "keycloak"
                        },
                        new
                        {
                            Id = "a9b0c1d2-e3f4-5678-2345-789012345678",
                            Description = "An authorization framework that enables applications to obtain limited access to user accounts. Industry standard for token-based authentication flows.",
                            Name = "OAuth 2.0",
                            Slug = "oauth2"
                        },
                        new
                        {
                            Id = "b0c1d2e3-f4a5-6789-3456-890123456789",
                            Description = "JSON Web Tokens are compact, URL-safe tokens for securely transmitting claims between parties. Commonly used for authentication and information exchange.",
                            Name = "JWT",
                            Slug = "jwt"
                        },
                        new
                        {
                            Id = "c1d2e3f4-a5b6-7890-4567-901234567890",
                            Description = "An OpenID Connect and OAuth 2.0 framework for ASP.NET Core. Provides centralized authentication and authorization for modern applications.",
                            Name = "Duende IdentityServer",
                            Slug = "identity-server"
                        },
                        new
                        {
                            Id = "d2e3f4a5-b6c7-8901-5678-012345678901",
                            Description = "A React framework for building fast, full-stack web apps with server-side rendering, routing, and static site generation.",
                            Name = "Next.js",
                            Slug = "nextjs"
                        },
                        new
                        {
                            Id = "e3f4a5b6-c7d8-9012-6789-123456789012",
                            Description = "A statically typed superset of JavaScript that compiles to clean JavaScript. Helps build large-scale apps with tooling support.",
                            Name = "TypeScript",
                            Slug = "typescript"
                        },
                        new
                        {
                            Id = "f4a5b6c7-d8e9-0123-7890-234567890123",
                            Description = "A JavaScript library for building user interfaces with component-based architecture. Developed by Meta with a large ecosystem and community.",
                            Name = "React",
                            Slug = "react"
                        },
                        new
                        {
                            Id = "a5b6c7d8-e9f0-1234-8901-345678901234",
                            Description = "A utility-first CSS framework for rapidly building custom user interfaces. Provides low-level utility classes for flexible, responsive designs.",
                            Name = "Tailwind CSS",
                            Slug = "tailwindcss"
                        },
                        new
                        {
                            Id = "b6c7d8e9-f0a1-2345-9012-456789012345",
                            Description = "An architectural style that structures an application as a collection of loosely coupled services that can be independently deployed and scaled.",
                            Name = "Microservices",
                            Slug = "microservices"
                        },
                        new
                        {
                            Id = "c7d8e9f0-a1b2-3456-0123-567890123456",
                            Description = "Command Query Responsibility Segregation separates read and write operations into different models. Enables optimized scaling and complex domain modeling.",
                            Name = "CQRS",
                            Slug = "cqrs"
                        },
                        new
                        {
                            Id = "d8e9f0a1-b2c3-4567-1234-678901234567",
                            Description = "A pattern where state changes are stored as a sequence of events. Provides complete audit trail and enables temporal queries and event replay.",
                            Name = "Event Sourcing",
                            Slug = "event-sourcing"
                        },
                        new
                        {
                            Id = "e9f0a1b2-c3d4-5678-2345-789012345678",
                            Description = "An approach to software development that centers the design on the core domain and domain logic. Emphasizes ubiquitous language and bounded contexts.",
                            Name = "Domain-Driven Design",
                            Slug = "ddd"
                        },
                        new
                        {
                            Id = "f0a1b2c3-d4e5-6789-3456-890123456789",
                            Description = "An architectural pattern that separates concerns into layers with dependencies pointing inward. Promotes testability, maintainability, and independence from frameworks.",
                            Name = "Clean Architecture",
                            Slug = "clean-architecture"
                        },
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7890-4567-901234567890",
                            Description = "A platform for developing, shipping, and running applications in containers. Enables consistent environments across development, testing, and production.",
                            Name = "Docker",
                            Slug = "docker"
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-8901-5678-012345678901",
                            Description = "An open-source container orchestration platform for automating deployment, scaling, and management of containerized applications across clusters.",
                            Name = "Kubernetes",
                            Slug = "kubernetes"
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-9012-6789-123456789012",
                            Description = "Microsoft's cloud computing platform offering IaaS, PaaS, and SaaS services. Provides deep integration with .NET and enterprise tooling.",
                            Name = "Microsoft Azure",
                            Slug = "azure"
                        },
                        new
                        {
                            Id = "d4e5f6a7-b8c9-0123-7890-234567890123",
                            Description = "A CI/CD platform integrated into GitHub for automating build, test, and deployment workflows. Uses YAML-based workflow definitions.",
                            Name = "GitHub Actions",
                            Slug = "github-actions"
                        },
                        new
                        {
                            Id = "e5f6a7b8-c9d0-1234-8901-345678901234",
                            Description = "An infrastructure as code tool for building, changing, and versioning cloud infrastructure safely and efficiently using declarative configuration.",
                            Name = "Terraform",
                            Slug = "terraform"
                        },
                        new
                        {
                            Id = "f6a7b8c9-d0e1-2345-9012-456789012345",
                            Description = "A free, open-source unit testing framework for .NET. Known for its extensibility, parallel test execution, and modern design patterns.",
                            Name = "xUnit",
                            Slug = "xunit"
                        },
                        new
                        {
                            Id = "a7b8c9d0-e1f2-3456-0123-567890123457",
                            Description = "Testing that verifies different modules or services work together correctly. In ASP.NET Core, often uses WebApplicationFactory for in-memory testing.",
                            Name = "Integration Testing",
                            Slug = "integration-testing"
                        },
                        new
                        {
                            Id = "b8c9d0e1-f2a3-4567-1234-678901234568",
                            Description = "A library that provides lightweight, throwaway instances of databases, message brokers, and other services in Docker containers for integration testing.",
                            Name = "Testcontainers",
                            Slug = "testcontainers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
